### ISSUE TITLE
[Bug] Homepage images too long (Safari on both macOS and iPhone)

### ISSUE THREAD

**Issue by Archibugiere** [eestec-milan/web#24]
https://github.com/eestec-milan/web/assets/81972898/ed222c2c-3e80-4c86-8184-8184bf330396

Same issue on iOS but worse.

**Comment by Lorenzo978** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Long Images](https://trello.com/c/LK4TwUQN/5-long-images)
