### ISSUE TITLE
Members

### ISSUE THREAD

**Issue by Lorenzo978** [eestec-milan/web#4]
# Description
Create the MESA members database and the page to manage it.

# Requirements
The member's table should hold information such as name, surname, email, phone, birthday, etc.
The meetings table should have a date and time
A member can take part in multiple meetings and the meetings are joined by various users.

There should be a new menu named "Members". Then there should be multiple sub-menus:
- [ ] Add member: form to add a new member
- [ ] Manage members: table using [Datatables.js](https://datatables.net/) with all the members and the possibility to filter them out. In each row, the name, surname, and meeting attendance count. Clicking the member will redirect to a form to change his/her data.

There should be a new menu named "Meetings". Here are multiple sub-menus:
- [ ] Add meeting: form to add a new meeting
- [ ] Register members: form with a select input to choose which meeting date and a table with all the members (each row name, username and a checkbox with default value "checked"). The admin should be able to filter the users and uncheck the members which have not joined the given meeting. Finally, a submit button to register the changes.

**Comment by TA50** [comment]
My Idea on this is to have three tables: 
1- Members: id, name, surname, email, phone_number, birthday, telegram_username,
2- Meetings: id, DateTime, location (this could be a geo-location or just an address? ), title, type (GM, scheduled, ... ) 
3- Attendances: id, member_id, meeting_id, (to establish a many-to-many relationship between members and meetings)
 (comment if you have any further info or ideas)

**Comment by Lorenzo978** [comment]
Sorry for the delay!

> 2- Meetings: id, DateTime, location (this could be a geo-location or just an address? ), title, type (GM, scheduled, ... )

1. Location could be just a string (like Leo 3.0.2 or whatever room they'll choose) 
2. Since the only attendance registered is the one at GMs, the type column is not needed.

The other points are correct :)
